//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadLibsGame {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileDisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileDisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MadLibsGame.FileDisplayNames", typeof(FileDisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America&apos;s Next Top Model Mad Libs.
        /// </summary>
        internal static string AmericasNextTopModelMadLibs {
            get {
                return ResourceManager.GetString("AmericasNextTopModelMadLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas Carol Mad Libs.
        /// </summary>
        internal static string ChristmasCarolMadLibs {
            get {
                return ResourceManager.GetString("ChristmasCarolMadLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas Mad Libs.
        /// </summary>
        internal static string ChristmasMadLibs {
            get {
                return ResourceManager.GetString("ChristmasMadLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool Mad Libs.
        /// </summary>
        internal static string CoolMadLibs {
            get {
                return ResourceManager.GetString("CoolMadLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On To MadLibs.
        /// </summary>
        internal static string LogOnToMadLibs {
            get {
                return ResourceManager.GetString("LogOnToMadLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mad Libs In Love.
        /// </summary>
        internal static string MadLibsInLove {
            get {
                return ResourceManager.GetString("MadLibsInLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster Mad Libs.
        /// </summary>
        internal static string MonsterMadLibs {
            get {
                return ResourceManager.GetString("MonsterMadLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Of The Living Mad Libs.
        /// </summary>
        internal static string NightOfLivingMadLibs {
            get {
                return ResourceManager.GetString("NightOfLivingMadLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off The Wall Mad Libs.
        /// </summary>
        internal static string OffTheWallMadLibs {
            get {
                return ResourceManager.GetString("OffTheWallMadLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Mad Libs.
        /// </summary>
        internal static string OriginalMadLibs {
            get {
                return ResourceManager.GetString("OriginalMadLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mad Libs For President.
        /// </summary>
        internal static string PresidentMadLibs {
            get {
                return ResourceManager.GetString("PresidentMadLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Of Mad Libs.
        /// </summary>
        internal static string SonOfMadLibs {
            get {
                return ResourceManager.GetString("SonOfMadLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sooper Dooper Mad Libs.
        /// </summary>
        internal static string SooperDooperMadLibs {
            get {
                return ResourceManager.GetString("SooperDooperMadLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation Fun Mad Libs.
        /// </summary>
        internal static string VacationMadLibs {
            get {
                return ResourceManager.GetString("VacationMadLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wacky Mad Libs.
        /// </summary>
        internal static string WackyMadLibs {
            get {
                return ResourceManager.GetString("WackyMadLibs", resourceCulture);
            }
        }
    }
}
