//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadLibsGame {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class MadLibsGameSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MadLibsGameSettings defaultInstance = ((MadLibsGameSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MadLibsGameSettings())));
        
        public static MadLibsGameSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../../Saved/SavedMadLibs.txt")]
        public string SavedMadLibsFilePath {
            get {
                return ((string)(this["SavedMadLibsFilePath"]));
            }
        }
    }
}
