//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadLibsGame {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PartsOfSpeechExamples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PartsOfSpeechExamples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MadLibsGame.PartsOfSpeechExamples", typeof(PartsOfSpeechExamples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kristen Wiig, Robert Downey Jr., Chris Pine, Zoe Saldana, Dwayne Johnson, Sylvester Stalone, Leslie Nielsen, Terry Crews, Bob Saget, Neil Patrick Harris.
        /// </summary>
        internal static string Actors {
            get {
                return ResourceManager.GetString("Actors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blue, messy, tired, unethical, damp, illuminated, quiet, aggressive, peaceful, dusty, acidic, obese, dehydrated, armed, frightened.
        /// </summary>
        internal static string Adjectives {
            get {
                return ResourceManager.GetString("Adjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quickly, foolishly, carefully, haphazardly, mockingly, inconspicuously, clumsily, expertly, enthusiastically, inappropriately, passionately, stealthily, unnaturally, randomly, reassuringly.
        /// </summary>
        internal static string Adverbs {
            get {
                return ResourceManager.GetString("Adverbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plant, mushroom, worm, bear, amoeba, plankton, starfish, human, platypus, pigeon.
        /// </summary>
        internal static string AliveSomethings {
            get {
                return ResourceManager.GetString("AliveSomethings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mold, trees, tigers, mushrooms, fish, humans, crickets, eagles, poison ivy, grass.
        /// </summary>
        internal static string AliveSomethingsPlural {
            get {
                return ResourceManager.GetString("AliveSomethingsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cow, sheep, pig, snake, shark, komodo dragon, zebra, octopus, polar bear, penguin.
        /// </summary>
        internal static string Animals {
            get {
                return ResourceManager.GetString("Animals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buffalo, snakes, horses, eagles, gophers, groundhogs, lions, jellyfish, turtles, monkeys.
        /// </summary>
        internal static string AnimalsPlural {
            get {
                return ResourceManager.GetString("AnimalsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to robin, eagle, phoenix, parrot, bluejay, raven, hawk, falcon, turkey, chicken.
        /// </summary>
        internal static string Birds {
            get {
                return ResourceManager.GetString("Birds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to James, Steve, Pablo, Chris, Eric, Kevin, Johnny, Tim, Aaron, Bruce.
        /// </summary>
        internal static string BoyNames {
            get {
                return ResourceManager.GetString("BoyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bank, post office, barn, skyscraper, hospital, condo, apartment, boathouse, stadium, school.
        /// </summary>
        internal static string Buildings {
            get {
                return ResourceManager.GetString("Buildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brad Pitt, Angelina Jolie, John Stewart, Paris Hilton, Chris Pratt, Morgan Freeman, Kim Kardashian, Elon Musk, Arnold Schwarzenegger, Tina Fey.
        /// </summary>
        internal static string Celebrities {
            get {
                return ResourceManager.GetString("Celebrities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baltimore, Cleveland, Chicago, San Francisco, Washington DC, Boston, Omaha, Las Vegas, New York City, Minneapolis.
        /// </summary>
        internal static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shirt, pants, socks, underwear, dress, stockings, overalls, sweater, sweatshirt, long underwear.
        /// </summary>
        internal static string Clothing {
            get {
                return ResourceManager.GetString("Clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shirts, sweatshirts, dresses, socks, underwear, stockings, mittens, gloves, pants, tuxedos.
        /// </summary>
        internal static string ClothingPlural {
            get {
                return ResourceManager.GetString("ClothingPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blue, red, black, pink, yellow, chartreuse, indigo, cyan, light green, greenish-yellow.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to independence, democracy, communism, fascism, socialism, tyranny, vigilantism, freedom, balance.
        /// </summary>
        internal static string Concepts {
            get {
                return ResourceManager.GetString("Concepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to box, bin, barrel, crate, tupperware, bag, folder, bottle, jar, bucket.
        /// </summary>
        internal static string Containers {
            get {
                return ResourceManager.GetString("Containers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolivia, Canada, China, Russia, Finland, South Africa, Japan, Zimbabwe, Mexico, Brazil.
        /// </summary>
        internal static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tuberculosis, chicken pox, the flu, strep throat, pink eye, dysentery, scurvy, black lung, asthma, gonorrhea.
        /// </summary>
        internal static string Diseases {
            get {
                return ResourceManager.GetString("Diseases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holy cow, Oh my god, Unbelievable, There&apos;s no way, I can&apos;t believe it, Ay dios mio, What in tarnation, Hallelujah.
        /// </summary>
        internal static string Exclamations {
            get {
                return ResourceManager.GetString("Exclamations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to George Washington, Bill Nye, Napoleon, Steven Spielberg, Vladimir Putin, Freddie Mercury, George Lucas, John Bon Jovi, Bill Gates, Jesus.
        /// </summary>
        internal static string FamousPeople {
            get {
                return ResourceManager.GetString("FamousPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprah Winfrey, Emma Watson, Ellen DeGeneres, Meryl Streep, Britney Spears, Lady Gaga, Kate Winslet, Raven Symone, Jennifer Lawrence, Amy Adams.
        /// </summary>
        internal static string FemaleCelebrities {
            get {
                return ResourceManager.GetString("FemaleCelebrities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carol, Jim, Steve, Julie, Chris, Stephanie, Matt, Mike, Alex, Britney.
        /// </summary>
        internal static string FirstNames {
            get {
                return ResourceManager.GetString("FirstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pizza, ice cream, popcorn, pudding, apple, salad, lasagna, tuna casserole, chicken noodle soup, taco.
        /// </summary>
        internal static string Foods {
            get {
                return ResourceManager.GetString("Foods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apples, sandwiches, eggs, salads, pretzels, blueberries, lima beans, omelets, energy bars, cookies.
        /// </summary>
        internal static string FoodsPlural {
            get {
                return ResourceManager.GetString("FoodsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apple, blueberry, watermelon, papaya, banana, grape, strawberry, melon, orange, raspberry, pineapple.
        /// </summary>
        internal static string Fruits {
            get {
                return ResourceManager.GetString("Fruits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apples, blueberries, watermelons, papayas, bananas, grapes, strawberries, melons, oranges, raspberries, pineapples.
        /// </summary>
        internal static string FruitsPlural {
            get {
                return ResourceManager.GetString("FruitsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to desk, dresser, couch, table, china cabinet, nightstand, tv stand, chair, bookshelf, stool.
        /// </summary>
        internal static string Furniture {
            get {
                return ResourceManager.GetString("Furniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopskotch, Capture The Flag, Monopoly, Four Square, Chutes and Ladders, Freeze Tag, Kan Jam, Duck Duck Goose, Chess, Apples To Apples.
        /// </summary>
        internal static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Grand Canyon, the Sahara Desert, Ohio, the North Pole, the outback, Antarctica, Russia, Rome, Mt. Everest, the Amazon Rainforest .
        /// </summary>
        internal static string GeographicalLocations {
            get {
                return ResourceManager.GetString("GeographicalLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to running, hiding, swimming, detecting, playing, sewing, eating, drinking, protesting, defending, cleaning, showering, drawing, stalling, erasing.
        /// </summary>
        internal static string GerundVerbs {
            get {
                return ResourceManager.GetString("GerundVerbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas, Thanksgiving, Independence Day, Boxing Day, Easter, Valentine&apos;s Day, New Year&apos;s Day, St. Patrick&apos;s Day, Halloween, Hanukkah, Kwanzaa.
        /// </summary>
        internal static string Holidays {
            get {
                return ResourceManager.GetString("Holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to living room, bathroom, kitchen, dining room, foyer, sitting room, bedroom, rec room, office, parlor.
        /// </summary>
        internal static string HouseRooms {
            get {
                return ResourceManager.GetString("HouseRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to earwax, fungus, collared greens, pus, squid, sludge, seaweed, slime, mucus, puke.
        /// </summary>
        internal static string IckySomethings {
            get {
                return ResourceManager.GetString("IckySomethings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ciao, prego, grazie, andiamo, giorno, primo, arancione, giallo, novanta, tredici.
        /// </summary>
        internal static string ItalianWords {
            get {
                return ResourceManager.GetString("ItalianWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smith, Jefferson, Howard, Brown, Doe, Gates, Watson, Jones, Stone, Johnson.
        /// </summary>
        internal static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A, Q, Z, T, W, P, N, R, X, O.
        /// </summary>
        internal static string Letters {
            get {
                return ResourceManager.GetString("Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to water, orange juice, gasoline, nail polish remover, paint thinner, grape soda, root beer, wine, hot sauce, Dr. Pepper.
        /// </summary>
        internal static string Liquids {
            get {
                return ResourceManager.GetString("Liquids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bono, Brad Pitt, Liam Neeson, Morgan Freeman, Adam Levine, Steven Spielberg, Adam Sandler, Barack Obama, Michael Jordan, Steve Harvey .
        /// </summary>
        internal static string MaleCelebrities {
            get {
                return ResourceManager.GetString("MaleCelebrities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leonardo DiCaprio, Owen Wilson, Drew Barrymore, Tom Hiddleston, Matthew McConaughey, Sandra Bullock, Kristen Stewart, Clint Eastwood, Robert Pattinson, Will Smith.
        /// </summary>
        internal static string MovieStars {
            get {
                return ResourceManager.GetString("MovieStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Smith, Carol Betty, Kara Tobey, Pete Barrett, June Arnold, Patti Ellis, Katie Sherman, Clint Holmes, Victoria Stanley, Joe Lloyd.
        /// </summary>
        internal static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mothrocid, metiverth, grasibleng, puriheed, ematorda, subdiroy, ablexine, fendant, closect, bounacconji.
        /// </summary>
        internal static string NonsenseWords {
            get {
                return ResourceManager.GetString("NonsenseWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tree, marker, toaster, chair, airplane, skyscraper, frisbee, hurricane, cloud, chalkboard, water fountain, pogo stick, fire extinguisher, window, flower pot.
        /// </summary>
        internal static string Nouns {
            get {
                return ResourceManager.GetString("Nouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lawyer, vacuum cleaner salesman, teacher, doctor, software developer, garbage collector, postal worker, carpenter, ditch digger, fast food worker.
        /// </summary>
        internal static string Occupations {
            get {
                return ResourceManager.GetString("Occupations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cashiers, mail carriers, musicians, coaches, priests, painters, baseball players, project managers, videogame designers.
        /// </summary>
        internal static string OccupationsPlural {
            get {
                return ResourceManager.GetString("OccupationsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nose, head, earlobe, armpit, heel, back, wrist, thumb, waist, elbow.
        /// </summary>
        internal static string PartsOfBody {
            get {
                return ResourceManager.GetString("PartsOfBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to knees, teeth, bones, arms, shoulder blades, knuckles, thumbs, ankles, nostrils.
        /// </summary>
        internal static string PartsOfBodyPlural {
            get {
                return ResourceManager.GetString("PartsOfBodyPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ate, jumped, ran, fell, rained, upset, disconnected, punched, chopped, built, closed, dropped, sat, threw, destroyed.
        /// </summary>
        internal static string PastTenseVerbs {
            get {
                return ResourceManager.GetString("PastTenseVerbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to McDonald’s, the Mississippi river, Mt Everest, the White House, Cleveland, Russia, the North Pole, Antarctica, the National Aquarium, Best Buy, the moon, the bathroom, Kentucky, the beach, Ireland.
        /// </summary>
        internal static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bananas, keys, boxes, sledgehammers, plants, branches, cars, road signs, strawberries, mirrors, chocolate chip cookies, trophies, shovels, blenders, chainsaws.
        /// </summary>
        internal static string PluralNouns {
            get {
                return ResourceManager.GetString("PluralNouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aunt, father, cousin, mother, uncle, brother, stepsister, great uncle, grandfather, second cousin.
        /// </summary>
        internal static string Relatives {
            get {
                return ResourceManager.GetString("Relatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ball, boulder, wheel, pie, circle, traffic circle, Mars, baseball, basketball, pizza.
        /// </summary>
        internal static string RoundSomethings {
            get {
                return ResourceManager.GetString("RoundSomethings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvard University, Yale University, Virginia Tech, State College, Boston College, UConn, University of Alabama, Howard Community College, Columbia University, Villanova University.
        /// </summary>
        internal static string SchoolNames {
            get {
                return ResourceManager.GetString("SchoolNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ah-ooh-ga, achoo, aroo, blam, biff, blop, clickety-clack, ding-dong, deed-a-reedle, d&apos;oh.
        /// </summary>
        internal static string SillyNoises {
            get {
                return ResourceManager.GetString("SillyNoises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brouhaha, canoodle, fuddy-duddy, gobbledygook, kerfuffle, lickspittle, malarkey, kooky, bugaboo, scuttlebutt.
        /// </summary>
        internal static string SillyWords {
            get {
                return ResourceManager.GetString("SillyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bumbershoots, flibbertigibbets, snollygosters, quires, ratoons, yarboroughs, borborygms, nincompoops, taradiddles, collywobbles.
        /// </summary>
        internal static string SillyWordsPlural {
            get {
                return ResourceManager.GetString("SillyWordsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hola, adios, telefono, pelota, camiseta, juego, bueno, panqueque, mundo, luz.
        /// </summary>
        internal static string SpanishWords {
            get {
                return ResourceManager.GetString("SpanishWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to baseball, football, tennis, soccer, water polo, basketball, hockey, ultimate frisbee, wrestling, lacrosse.
        /// </summary>
        internal static string Sports {
            get {
                return ResourceManager.GetString("Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to biggest, loudest, best, dirtiest, smallest, driest, creepiest, silliest, oldest, coldest.
        /// </summary>
        internal static string Superlatives {
            get {
                return ResourceManager.GetString("Superlatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franklin, Arlington, Salem, Springfield, Columbia, Georgetown, Washington, Riverside, Kingston, Northfield, Frederick.
        /// </summary>
        internal static string Towns {
            get {
                return ResourceManager.GetString("Towns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jim Parsons, Hugh Laurie, Amanda Bynes, Selena Gomez, Nina Dobrev, Ray Romano, Danny Trejo, Rowan Atkinson, Tina Fey, Zooey Deschanel.
        /// </summary>
        internal static string TVActors {
            get {
                return ResourceManager.GetString("TVActors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to celery, carrot, spinach, squash, pepper, kale, lima bean, green bean, cauliflower, broccoli.
        /// </summary>
        internal static string Vegetables {
            get {
                return ResourceManager.GetString("Vegetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car, train, airplane, bike, motorcycle, scooter, racecar, 18-wheeler, tank, tricycle.
        /// </summary>
        internal static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swim, laugh, fall, roll, explode, disintegrate, jump, eat, sleep, write, swallow, shrink, fight, electrocute, throw.
        /// </summary>
        internal static string Verbs {
            get {
                return ResourceManager.GetString("Verbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jumps, runs, eats, explodes, slips, builds, freezes, cooks, stuffs, electrocutes.
        /// </summary>
        internal static string VerbsEndingInS {
            get {
                return ResourceManager.GetString("VerbsEndingInS", resourceCulture);
            }
        }
    }
}
